### ISSUE TITLE
Pin Python to >=3.8,<3.11

### ISSUE THREAD

**Issue by hoechenberger** [conda-forge/mne-feedstock#116]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I installed mne-base and then decided to "upgrade" to mne. But I ran into package resolution problems because during the mne-base install, I received Python 3.11, which apparently (?) doesn't want to live together with mne and its dependencies, at least on my Apple Silicon computer. I haven't done any extensive testing, though

### Installed packages

```shell
...
```

### Environment info

```shell
...
```

**Comment by larsoner** [comment]
Numba with 3.11 is about to land, so I'll optimistically close this. We can reopen if https://github.com/mne-tools/mne-installers/pull/186 fails
