### ISSUE TITLE
Switch build backend to `hatchling`

### ISSUE THREAD

**Issue by hoechenberger** [conda-forge/mne-feedstock#132]
For whatever obscure reason, our builds here are working even though we're not installing all required build deps (still using `setuptools` instead of `hatchling`)

The `host` requirements should be updated to include 

```
    - hatchling
    - hatch-vcs
```

@larsoner would you like to give it a shot if you have time?

**Comment by larsoner** [comment]
Not tomorrow, Tuesday

**Comment by hoechenberger** [comment]
@conda-forge/python Hello! We'd just like to bring your attention to the fact that this package's build backend was changed to `hatchling` (with `hatch-vcs`) upstream, and we forgot to update the feedstock – it would install `pip`, `setuptools`, `setuptools-scm`, and `git`; i.e., the new build deps were missing. However, builds still succeeded! We were wondering if this points to a problem with build isolation on condo-forge?

**Comment by xhochy** [comment]
You ran into https://github.com/conda/conda-build/issues/3993
