### ISSUE TITLE
0.20 packages

### ISSUE THREAD

**Issue by hoechenberger** [conda-forge/mne-feedstock#25]
There are currently no 0.20 packages on anaconda.org. Apparently the build failed.

**Comment by hoechenberger** [comment]
Also we should check & update the dependencies. For example, we now require pyvista 0.24, etc. I can help with that sometime tomorrow.

**Comment by christianbrodbeck** [comment]
There was an obscure error in the 0.20 build. If you create a PR with updated requirements then we can see if the error recurs and what we can do about it...

**Comment by hoechenberger** [comment]
Yes @christianbrodbeck, I will look into this either later today or tomorrow.

**Comment by larsoner** [comment]
This was the problematic PR

https://github.com/conda-forge/mne-feedstock/pull/24
