### ISSUE TITLE
BUG: mne-qt-browser missing in recipe

### ISSUE THREAD

**Issue by marsipu** [conda-forge/mne-feedstock#57]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

## Issue:
When `mne` is installed via conda, the new browser-backend `mne-qt-browser` which is part of `mne` since version 0.24. isn't installed with it. It is probably missing in the recipe.

## Code reproducing the problem:
```bash
conda create -n mne -c conda-forge mne
```

## Expected result:
`mne-qt-browser` found in installed packages.

**Comment by larsoner** [comment]
PR welcome
